- name: Disable default version of NodeJS in the system
  ansible.builtin.shell: dnf module disable nodejs -y

- name: Disable default version of NodeJS in the system
  ansible.builtin.shell: dnf module enable nodejs:18 -y

- name: Install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: installed

- name: Copy backend.service configuration file
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: Add the application user 'expense'
  ansible.builtin.user:
    name: expense

- name: Delete existing App Content
  ansible.builtin.file:
    path: /app
    state: absent

- name: Create app folder
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download and Unzip App Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: yes

- name: Download dependencies
  community.general.npm:
    path: /app

- name: Restart service
  ansible.builtin.systemd_service:
    name: backend
    state: restarted
    enabled: true

- name: install mysql client
  ansible.builtin.dnf:
    name: mysql
    state: installed

- name: Load schema
  ansible.builtin.shell: mysql -h 172.31.32.243 -uroot -pExpenseApp@1 < /app/schema/backend.sql
