- name: Install the latest version of Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy expense configuration file
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Delete existing App Content
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create html folder which was deleted in previous step
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory


- name: Download and Unzip App Content
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Enable and restart nginx service
  ansible.builtin.systemd_service:
    name: nginx
    enabled: true
    state: restarted